# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 24 Jun 2019 18:25:30 +0000
*               @ALL          1
*               @user         8
